version: '3.6'
services:
  dbserver:
    container_name: mysql_java
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: springdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    volumes:
      # 起動スクリプト
      - ./docker/sql:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./docker/mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis-server:
    container_name: redis-server
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
    restart: always
    tty: true
  app1:
    container_name: spring_app1
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8081:8080"
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  app2:
    container_name: spring_app2
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8082:8080"
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  app3:
    container_name: spring_app3
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8083:8080"
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  web-server:
    container_name: nginx-server
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    depends_on: 
      - app1
      - app2
      - app3
    tty: true
    # links: 
    #   - app1
    #   - app2
    #   - app3