version: '3.6'
services:
  dbserver:
    container_name: mysql_java
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: springdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    # expose:
    #   - 3306
    ports:
      - 3306:3306
    volumes:
      # 起動スクリプト
      - ./docker/sql:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./docker/mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis-server:
    container_name: redis-server
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
    restart: always
    tty: true
  app1:
    container_name: spring_app1
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8081:8081"
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  app2:
    container_name: spring_app2
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8082:8082"
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  app3:
    container_name: spring_app3
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis-server
    ports:
      - "8083:8083"
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true