version: '3.6'
services:
  dbserver:
    container_name: mysql_java
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: springdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    volumes:
      # 起動スクリプト
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./docker/mysql/volumes:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis_server:
    container_name: redis_server
    image: redis:latest
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
    restart: always
    tty: true
  api1:
    container_name: spring_api1
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis_server
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  api2:
    container_name: spring_api2
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis_server
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  api3:
    container_name: spring_api3
    image: openjdk:16
    depends_on: 
      - dbserver
      - redis_server
    expose:
      - 8080
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    tty: true
  nginx_server:
    container_name: nginx_server
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    depends_on: 
      - api1
      - api2
      - api3
    tty: true
    # links: 
    #   - api1
    #   - api2
    #   - api3