FROM nginx:latest
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# # RUN: docker buildするときに実行される
# RUN echo "now building..."
# # CMD: docker runするときに実行される
# CMD echo "now running..."